# Generated by Django 3.2 on 2021-04-29 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200, verbose_name='name')),
                ('article_text', models.TextField(verbose_name='textpage')),
                ('pub_date', models.DateTimeField(verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=200, verbose_name='name')),
                ('link_url', models.CharField(max_length=200, verbose_name='url')),
                ('link_views', models.IntegerField(verbose_name='views')),
            ],
        ),
        migrations.CreateModel(
            name='user_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_author', models.CharField(max_length=150, verbose_name='authorname')),
                ('link_name', models.CharField(max_length=200, verbose_name='name')),
                ('link_url', models.CharField(max_length=200, verbose_name='url')),
                ('link_views', models.IntegerField(verbose_name='views')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='authorname')),
                ('comment_text', models.CharField(max_length=200, verbose_name='text')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.article')),
            ],
        ),
    ]
